<?php
require "config/config.ini"; 
$urlLing="index.php";
$img = "bra.png";
$tipoLinguagem = "BRA";
$resultadopaginas = mysqli_query($conexao, "SELECT * from paginas_en");
$totalpaginas = mysqli_num_rows($resultadopaginas);
$resultadohome = mysqli_query($conexao, "SELECT * from home_en");
$totalhome = mysqli_num_rows($resultadohome);
$resultadoquemSomos = mysqli_query($conexao, "SELECT * from quemSomos_en");
$totalquemSomos = mysqli_num_rows($resultadoquemSomos);
$resultadopro = mysqli_query($conexao, "SELECT * from produtos_en");
$totalpro = mysqli_num_rows($resultadopro);
$resultadoprocesses = mysqli_query($conexao, "SELECT * from processos_en");
$totalprocessos = mysqli_num_rows($resultadoprocesses);
$resultadoClientes = mysqli_query($conexao, "SELECT * from clientes");
$totalClientes = mysqli_num_rows($resultadoClientes);
$resultadoCertificados = mysqli_query($conexao, "SELECT * from certificados");
$totalCertificados = mysqli_num_rows($resultadoCertificados);
$resultadolocalizacao = mysqli_query($conexao, "SELECT * from empresa_en");
$totalempresa = mysqli_num_rows($resultadolocalizacao);
$resultadoprodutos = mysqli_query($conexao, "SELECT * from produtos_en");
$totalprodutos = mysqli_num_rows($resultadoprodutos);
$resultadocert = mysqli_query($conexao, "SELECT * from certificados");
$totalcert = mysqli_num_rows($resultadocert);
$nomeContato="Your Name";
$telefoneContato="Your Phone";
$emailContato="Your Email";
$mensagemContato="Message";
include "index.php";