<?php
require "config/config.ini"; 
$urlLing="index.php";
$img = "bra.png";
$tipoLinguagem = "BRA";
$pag="paginas_en";
$hom="home_en";
$qms="quemSomos_en";
$prod="produtos_en";
$proc="processos_en";
$emp="empresa_en";
$nomeContato="Your Name";
$telefoneContato="Your Phone";
$emailContato="Your Email";
$mensagemContato="Message";
$msgNomeContat="Please enter your name.";
$msgEmailContat="Please enter your email.";
$msgTelContat="Please enter your phone number.";
$msgMensagemContat="Please enter a message.";
$botaoM="Send Message";
$botaoProd="Close Product";
$botaoPdf="Close PDF";
include "index.php";